application:
  name: test
  host: "0.0.0.0"
  port: "3000"
  version: v1.0.0
  secret: "123456"
logger:
  # 日志存放路径
  path: files/logs
  # 日志输出，file：文件，default：命令行，其他：命令行
  stdout: '' #控制台日志，启用后，不输出到文件
  # 日志等级, trace, debug, info, warn, error, fatal
  level: trace
  # 支持default、zap、logrus
  type: default
  # 单文件条数
  cap: 100

# 如果邮件配置中的内容为空，则不会发送邮件，不影响程序运行
email:
  host: 邮箱服务地址
  port: 465
  username: 邮箱账户
  password: 邮箱密钥
  # 发送者邮箱地址
  fromEmail: 发件邮箱
  # 邮件内容格式
  contentType: text/plain
  # 邮件标题前缀
  subjectPrefix: ethereum
  # 多个地址用英文逗号隔开
  toEmail: 收件邮箱
  # 监控信息简报发送间隔时间，单位秒；每隔指定时间，会将监控设备的节点概要信息发送到邮箱
  monitorTime: 86400
